name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u vakinduphilliam -p dckr_pat_0tna62JZudsw2D4TM0hLhifmBng 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$(date +%s)
      
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME 
